// LOCALHOST
###
GET http://localhost:8080/contacts 
###
GET http://localhost:8080/contacts/63fc33736f65ed12b99d6328
###
GET http://localhost:8080/contacts/63fc33736f65ed12b99d6329
###
GET http://localhost:8080/contacts/63fc33736f65ed12b99d632a

// PRODUCTION Deploy

###
GET https://cse341-javier-espinoza.onrender.com

